window.VOCAB_GROUPS=[
{t:'transition · tradition · traditionally',n:'transition 以 trans- 开头，表示从一种状态跨到另一种状态；tradition 和 traditionally 都与“传统”有关。',w:[['transition','过渡语；转变','a phrase that indicates the <mark>connections between ideas</mark>','Intro 1.8'],['tradition','传统；世代相传的习俗','a long-established custom <mark>passed down by many generations</mark> in a society','Intro 1.8'],['traditionally','传统上；依照传统','as part of a <mark>long-established practice</mark> or belief','PV 1.8']]},
{t:'destination · donation',n:'destination 中间是 destina-，表示要到达的地点；donation 中间是 dona-，来自 donate，表示捐赠物。',w:[['destination','目的地','the <mark>place someone is going</mark>','Intro 1.8'],['donation','捐赠物；捐款','something <mark>given to charity</mark>, especially money','PV 3.1']]},
{t:'disaster · desert',n:'disaster 是“灾难”；desert 少一个 a，表示“沙漠”。读音也不同。',w:[['disaster','灾难；灾害','a sudden event that causes <mark>great damage or loss of life</mark>','PV 1.8'],['desert','沙漠；荒漠','a <mark>dry, barren area of land</mark>','SF 4.8']]},
{t:'industrial · indigenous',n:'industrial 与 industry 有关，表示工业的；indigenous 表示某地原生、本土的。注意 indu- 和 indi-。',w:[['industrial','工业的','relating to the <mark>manufacture of goods from raw materials</mark>','SF 2.8'],['indigenous','本土的；当地原生的','originating or occurring <mark>naturally in a particular place</mark>','PV 2.1']]},
{t:'nationality · nutritional',n:'nationality 来自 nation，表示国籍；nutritional 来自 nutrition，表示营养的。开头分别是 nat- 和 nutri-。',w:[['nationality','国籍','the status of <mark>belonging to a particular country</mark>','IV 1.8 / PV 3.8'],['nutritional','营养的','providing substances <mark>necessary for growth and good health</mark>','SF 2.8']]},
{t:'displaced · disposable',n:'displaced 表示被移离原位；disposable 表示用完即可丢弃。中间分别是 place 和 posa。',w:[['displaced','移位的；流离失所的','<mark>moved from its usual position</mark>','PV 1.8'],['disposable','一次性的','<mark>intended to be used only once</mark>','SF 4.8']]},
{t:'overseas · overuse',n:'overseas 是 over + seas，在海外；overuse 是 over + use，过度使用。',w:[['overseas','在海外；在国外','<mark>in another country</mark>','PV 3.1'],['overuse','过度使用','<mark>using something too much</mark>','SF 1.8']]},
{t:'preservation · participation',n:'preservation 来自 preserve，表示保护；participation 来自 participate，表示参与。长词先抓中间的 preserv- 与 particip-。',w:[['preservation','保护；保存','the act of maintaining something and <mark>keeping it safe</mark>','PV 3.1'],['participation','参与','the action of <mark>joining in something</mark>','PV 3.8']]},
{t:'comprehension · comprehensive',n:'comprehension 是名词“理解”；comprehensive 是形容词“全面的”。结尾 -sion 与 -sive 是关键。',w:[['comprehension','理解；理解力','the action of <mark>understanding something</mark>','Intro 1.1'],['comprehensive','全面的；综合的','complete; <mark>including all the elements</mark> of something','PV 3.8']]},
{t:'intercultural · interpersonal · internally',n:'intercultural 是文化之间；interpersonal 是人与人之间；internally 是内部地。先看 inter 后面的 cultural / personal，以及 internal。',w:[['intercultural','跨文化的；不同文化之间的','between <mark>different societies or countries</mark>','IV 1.8'],['interpersonal','人际的；人与人之间的','the <mark>relationship between people</mark>','IV 1.8'],['internally','内部地；从内部','<mark>coming from within</mark>','PV 1.8']]},
{t:'productivity · creativity',n:'productivity 来自 product，表示生产效率；creativity 来自 create，表示创造力。两者都以 -tivity 结尾。',w:[['productivity','生产力；生产效率','<mark>the amount of things made</mark>','PV 4.1'],['creativity','创造力','the <mark>use of imagination or original ideas</mark>','SF 4.1']]},
{t:'manufacture · machinery',n:'manufacture 是制造这一动作；machinery 是机器设备。两词都与生产有关，但词形和词性不同。',w:[['manufacture','制造；生产','<mark>to make; to produce</mark>','SF 2.8'],['machinery','机器；机械设备','<mark>equipment</mark>','PV 4.1']]},
{t:'authority · charity',n:'authority 表示权威或当局；charity 表示慈善。它们结尾相像，但开头 auth- 与 char- 完全不同。',w:[['authority','权威人士；当局','one with the <mark>power to make decisions</mark>','Intro 1.1'],['charity','慈善','the voluntary <mark>giving of help to those in need</mark>','PV 2.8']]},
{t:'harmony · harm',n:'harmony 是和谐；harm 是伤害。不要因为 harmony 里含有 harm 的字母就把意思联系起来。',w:[['harmony','和谐','forming a <mark>pleasing and consistent whole</mark>','PV 3.8'],['harm','伤害；损害','<mark>physical injury or mental damage</mark>; hurt','SF 4.1']]},
{t:'restore · forestry',n:'restore 是恢复；forestry 是林业。两词都有 -stor- / -restr- 的视觉相似部分，但词根不同。',w:[['restore','恢复；修复','<mark>bring back</mark>; put back into the original condition','PV 3.8 / SF 1.8'],['forestry','林业；森林管理','the <mark>planting, managing, and caring for forests</mark>','SF 4.8']]},
{t:'sickness · species',n:'sickness 表示疾病；species 表示物种。开头都像 s-i-c/s-p-e，快速扫读时尤其容易看错。',w:[['sickness','疾病','<mark>state of being ill</mark>','PV 2.8'],['species','物种','a <mark>type of living thing</mark>','SF 4.1']]},
{t:'uneducated · uncomfortable · unfortunate · unwanted · unplug',n:'这一组都以 un- 开头。背诵时不要只认前缀，要继续看 educated、comfortable、fortunate、wanted、plug。',w:[['uneducated','未受教育的','<mark>lacking schooling</mark>','PV 2.8'],['uncomfortable','不舒服的','causing <mark>slight pain, worry, or unease</mark>','PV 3.8'],['unfortunate','不幸的；倒霉的','<mark>bad and/or unlucky</mark>','PV 4.1'],['unwanted','不需要的','<mark>no longer desired</mark>','SF 2.8'],['unplug','拔掉插头；断开电源','<mark>disconnect</mark>; remove from a socket','SF 4.8']]}
];